### ISSUE TITLE
"Get nanj rate" does not work on Post

### ISSUE THREAD

**Issue by mitchydeath** [NANJ-COIN/web-api#1]
I Post requested "Get nanj rate" but 404 is returned.
And Get Request returns a normal response.
Therefore, don't need to add ContentType to RequestHeader.←It's about Readme

**Comment by VoDongMy** [comment]
Thank you for issue contact.
that is my mistake when make readme file. Exactly this API use method GET. Its purpose is to return Nanj rate with unit of money symbol you require ex: JPY or USD
