### ISSUE TITLE
The property name of the statusCode of CreateWallet is status

### ISSUE THREAD

**Issue by mitchydeath** [NANJ-COIN/web-api#4]
In the case of CreateWallet, the status name of the StatusCode included in Response is "status".
In other APIs it is "statusCode".

**Comment by VoDongMy** [comment]
all the APIs have property names statusCode, that is the number, our API will return semantically valid statusCode response codes based on the success of your request.
We will constantly improve, so that the APIs to better.
Thank your so much.
